/* 
 * Contratti API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AooUtentiRequest
    /// </summary>
    [DataContract]
    public partial class AooUtentiRequest :  IEquatable<AooUtentiRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AooUtentiRequest" /> class.
        /// </summary>
        /// <param name="utenti">utenti.</param>
        public AooUtentiRequest(List<AooUtenteRequest> utenti = default(List<AooUtenteRequest>))
        {
            this.Utenti = utenti;
        }
        
        /// <summary>
        /// Gets or Sets Utenti
        /// </summary>
        [DataMember(Name="utenti", EmitDefaultValue=false)]
        public List<AooUtenteRequest> Utenti { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AooUtentiRequest {\n");
            sb.Append("  Utenti: ").Append(Utenti).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AooUtentiRequest);
        }

        /// <summary>
        /// Returns true if AooUtentiRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AooUtentiRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AooUtentiRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Utenti == input.Utenti ||
                    this.Utenti != null &&
                    this.Utenti.SequenceEqual(input.Utenti)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Utenti != null)
                    hashCode = hashCode * 59 + this.Utenti.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
