/* 
 * Contratti API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ClassiDocumentaliRequest
    /// </summary>
    [DataContract]
    public partial class ClassiDocumentaliRequest :  IEquatable<ClassiDocumentaliRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassiDocumentaliRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ClassiDocumentaliRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassiDocumentaliRequest" /> class.
        /// </summary>
        /// <param name="classi">classi (required).</param>
        public ClassiDocumentaliRequest(List<ClasseDocumentaleRequest> classi = default(List<ClasseDocumentaleRequest>))
        {
            // to ensure "classi" is required (not null)
            if (classi == null)
            {
                throw new InvalidDataException("classi is a required property for ClassiDocumentaliRequest and cannot be null");
            }
            else
            {
                this.Classi = classi;
            }
        }
        
        /// <summary>
        /// Gets or Sets Classi
        /// </summary>
        [DataMember(Name="classi", EmitDefaultValue=false)]
        public List<ClasseDocumentaleRequest> Classi { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClassiDocumentaliRequest {\n");
            sb.Append("  Classi: ").Append(Classi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClassiDocumentaliRequest);
        }

        /// <summary>
        /// Returns true if ClassiDocumentaliRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ClassiDocumentaliRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClassiDocumentaliRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Classi == input.Classi ||
                    this.Classi != null &&
                    this.Classi.SequenceEqual(input.Classi)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Classi != null)
                    hashCode = hashCode * 59 + this.Classi.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
