/* 
 * Contratti API V2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ClienteFinaleClienteRequest
    /// </summary>
    [DataContract]
    public partial class ClienteFinaleClienteRequest :  IEquatable<ClienteFinaleClienteRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClienteFinaleClienteRequest" /> class.
        /// </summary>
        /// <param name="identificativoCliente">identificativoCliente.</param>
        /// <param name="cliente">cliente.</param>
        public ClienteFinaleClienteRequest(string identificativoCliente = default(string), ClienteRequest cliente = default(ClienteRequest))
        {
            this.IdentificativoCliente = identificativoCliente;
            this.Cliente = cliente;
        }
        
        /// <summary>
        /// Gets or Sets IdentificativoCliente
        /// </summary>
        [DataMember(Name="identificativoCliente", EmitDefaultValue=false)]
        public string IdentificativoCliente { get; set; }

        /// <summary>
        /// Gets or Sets Cliente
        /// </summary>
        [DataMember(Name="cliente", EmitDefaultValue=false)]
        public ClienteRequest Cliente { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClienteFinaleClienteRequest {\n");
            sb.Append("  IdentificativoCliente: ").Append(IdentificativoCliente).Append("\n");
            sb.Append("  Cliente: ").Append(Cliente).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClienteFinaleClienteRequest);
        }

        /// <summary>
        /// Returns true if ClienteFinaleClienteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ClienteFinaleClienteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClienteFinaleClienteRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdentificativoCliente == input.IdentificativoCliente ||
                    (this.IdentificativoCliente != null &&
                    this.IdentificativoCliente.Equals(input.IdentificativoCliente))
                ) && 
                (
                    this.Cliente == input.Cliente ||
                    (this.Cliente != null &&
                    this.Cliente.Equals(input.Cliente))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdentificativoCliente != null)
                    hashCode = hashCode * 59 + this.IdentificativoCliente.GetHashCode();
                if (this.Cliente != null)
                    hashCode = hashCode * 59 + this.Cliente.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
