/* 
 * Contratti API V2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ContrattoSaveRequest
    /// </summary>
    [DataContract]
    public partial class ContrattoSaveRequest :  IEquatable<ContrattoSaveRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines TipoSalvataggio
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TipoSalvataggioEnum
        {
            
            /// <summary>
            /// Enum CREA for value: CREA
            /// </summary>
            [EnumMember(Value = "CREA")]
            CREA = 1
        }

        /// <summary>
        /// Gets or Sets TipoSalvataggio
        /// </summary>
        [DataMember(Name="tipoSalvataggio", EmitDefaultValue=false)]
        public TipoSalvataggioEnum TipoSalvataggio { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContrattoSaveRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContrattoSaveRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContrattoSaveRequest" /> class.
        /// </summary>
        /// <param name="tipoSalvataggio">tipoSalvataggio (required).</param>
        public ContrattoSaveRequest(TipoSalvataggioEnum tipoSalvataggio = default(TipoSalvataggioEnum))
        {
            // to ensure "tipoSalvataggio" is required (not null)
            if (tipoSalvataggio == null)
            {
                throw new InvalidDataException("tipoSalvataggio is a required property for ContrattoSaveRequest and cannot be null");
            }
            else
            {
                this.TipoSalvataggio = tipoSalvataggio;
            }
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContrattoSaveRequest {\n");
            sb.Append("  TipoSalvataggio: ").Append(TipoSalvataggio).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ContrattoSaveRequest);
        }

        /// <summary>
        /// Returns true if ContrattoSaveRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ContrattoSaveRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContrattoSaveRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TipoSalvataggio == input.TipoSalvataggio ||
                    (this.TipoSalvataggio != null &&
                    this.TipoSalvataggio.Equals(input.TipoSalvataggio))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TipoSalvataggio != null)
                    hashCode = hashCode * 59 + this.TipoSalvataggio.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
