/* 
 * Contratti API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GruppoAziendeModuloIxCeRequest
    /// </summary>
    [DataContract]
    public partial class GruppoAziendeModuloIxCeRequest :  IEquatable<GruppoAziendeModuloIxCeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GruppoAziendeModuloIxCeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GruppoAziendeModuloIxCeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GruppoAziendeModuloIxCeRequest" /> class.
        /// </summary>
        /// <param name="fascia">fascia (required).</param>
        /// <param name="fasciaAnniSuccessiva">fasciaAnniSuccessiva.</param>
        /// <param name="responsabileConservazione">responsabileConservazione.</param>
        public GruppoAziendeModuloIxCeRequest(FasciaIxCeInfo fascia = default(FasciaIxCeInfo), FasciaIxCeInfo fasciaAnniSuccessiva = default(FasciaIxCeInfo), ResponsabileConservazioneInfo responsabileConservazione = default(ResponsabileConservazioneInfo))
        {
            // to ensure "fascia" is required (not null)
            if (fascia == null)
            {
                throw new InvalidDataException("fascia is a required property for GruppoAziendeModuloIxCeRequest and cannot be null");
            }
            else
            {
                this.Fascia = fascia;
            }
            this.FasciaAnniSuccessiva = fasciaAnniSuccessiva;
            this.ResponsabileConservazione = responsabileConservazione;
        }
        
        /// <summary>
        /// Gets or Sets Fascia
        /// </summary>
        [DataMember(Name="fascia", EmitDefaultValue=false)]
        public FasciaIxCeInfo Fascia { get; set; }

        /// <summary>
        /// Gets or Sets FasciaAnniSuccessiva
        /// </summary>
        [DataMember(Name="fasciaAnniSuccessiva", EmitDefaultValue=false)]
        public FasciaIxCeInfo FasciaAnniSuccessiva { get; set; }

        /// <summary>
        /// Gets or Sets ResponsabileConservazione
        /// </summary>
        [DataMember(Name="responsabileConservazione", EmitDefaultValue=false)]
        public ResponsabileConservazioneInfo ResponsabileConservazione { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GruppoAziendeModuloIxCeRequest {\n");
            sb.Append("  Fascia: ").Append(Fascia).Append("\n");
            sb.Append("  FasciaAnniSuccessiva: ").Append(FasciaAnniSuccessiva).Append("\n");
            sb.Append("  ResponsabileConservazione: ").Append(ResponsabileConservazione).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GruppoAziendeModuloIxCeRequest);
        }

        /// <summary>
        /// Returns true if GruppoAziendeModuloIxCeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GruppoAziendeModuloIxCeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GruppoAziendeModuloIxCeRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Fascia == input.Fascia ||
                    (this.Fascia != null &&
                    this.Fascia.Equals(input.Fascia))
                ) && 
                (
                    this.FasciaAnniSuccessiva == input.FasciaAnniSuccessiva ||
                    (this.FasciaAnniSuccessiva != null &&
                    this.FasciaAnniSuccessiva.Equals(input.FasciaAnniSuccessiva))
                ) && 
                (
                    this.ResponsabileConservazione == input.ResponsabileConservazione ||
                    (this.ResponsabileConservazione != null &&
                    this.ResponsabileConservazione.Equals(input.ResponsabileConservazione))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Fascia != null)
                    hashCode = hashCode * 59 + this.Fascia.GetHashCode();
                if (this.FasciaAnniSuccessiva != null)
                    hashCode = hashCode * 59 + this.FasciaAnniSuccessiva.GetHashCode();
                if (this.ResponsabileConservazione != null)
                    hashCode = hashCode * 59 + this.ResponsabileConservazione.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
