/* 
 * Contratti API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RuoloConservazioneRequest
    /// </summary>
    [DataContract]
    public partial class RuoloConservazioneRequest :  IEquatable<RuoloConservazioneRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines Ruolo
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RuoloEnum
        {
            
            /// <summary>
            /// Enum Produttore for value: Produttore
            /// </summary>
            [EnumMember(Value = "Produttore")]
            Produttore = 1,
            
            /// <summary>
            /// Enum Utente for value: Utente
            /// </summary>
            [EnumMember(Value = "Utente")]
            Utente = 2
        }

        /// <summary>
        /// Gets or Sets Ruolo
        /// </summary>
        [DataMember(Name="ruolo", EmitDefaultValue=false)]
        public RuoloEnum Ruolo { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RuoloConservazioneRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RuoloConservazioneRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RuoloConservazioneRequest" /> class.
        /// </summary>
        /// <param name="ruolo">ruolo (required).</param>
        public RuoloConservazioneRequest(RuoloEnum ruolo = default(RuoloEnum))
        {
            // to ensure "ruolo" is required (not null)
            if (ruolo == null)
            {
                throw new InvalidDataException("ruolo is a required property for RuoloConservazioneRequest and cannot be null");
            }
            else
            {
                this.Ruolo = ruolo;
            }
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RuoloConservazioneRequest {\n");
            sb.Append("  Ruolo: ").Append(Ruolo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RuoloConservazioneRequest);
        }

        /// <summary>
        /// Returns true if RuoloConservazioneRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RuoloConservazioneRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RuoloConservazioneRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Ruolo == input.Ruolo ||
                    (this.Ruolo != null &&
                    this.Ruolo.Equals(input.Ruolo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ruolo != null)
                    hashCode = hashCode * 59 + this.Ruolo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
