/* 
 * Contratti API V2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICreazioneContrattoApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>CreateContrattoResponse</returns>
        CreateContrattoResponse CreateContrattoAggiuntaDitte (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization);

        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of CreateContrattoResponse</returns>
        ApiResponse<CreateContrattoResponse> CreateContrattoAggiuntaDitteWithHttpInfo (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization);
        /// <summary>
        /// Crea un contratto cliente standard
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>CreateContrattoResponse</returns>
        CreateContrattoResponse CreateContrattoClienteStandard (CreateContrattoRequest contratto, string xAuthorization);

        /// <summary>
        /// Crea un contratto cliente standard
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of CreateContrattoResponse</returns>
        ApiResponse<CreateContrattoResponse> CreateContrattoClienteStandardWithHttpInfo (CreateContrattoRequest contratto, string xAuthorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of CreateContrattoResponse</returns>
        System.Threading.Tasks.Task<CreateContrattoResponse> CreateContrattoAggiuntaDitteAsync (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization);

        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (CreateContrattoResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateContrattoResponse>> CreateContrattoAggiuntaDitteAsyncWithHttpInfo (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization);
        /// <summary>
        /// Crea un contratto cliente standard
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of CreateContrattoResponse</returns>
        System.Threading.Tasks.Task<CreateContrattoResponse> CreateContrattoClienteStandardAsync (CreateContrattoRequest contratto, string xAuthorization);

        /// <summary>
        /// Crea un contratto cliente standard
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (CreateContrattoResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateContrattoResponse>> CreateContrattoClienteStandardAsyncWithHttpInfo (CreateContrattoRequest contratto, string xAuthorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CreazioneContrattoApi : ICreazioneContrattoApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CreazioneContrattoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CreazioneContrattoApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreazioneContrattoApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CreazioneContrattoApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>CreateContrattoResponse</returns>
        public CreateContrattoResponse CreateContrattoAggiuntaDitte (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization)
        {
             ApiResponse<CreateContrattoResponse> localVarResponse = CreateContrattoAggiuntaDitteWithHttpInfo(identificativoCliente, contratto, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of CreateContrattoResponse</returns>
        public ApiResponse< CreateContrattoResponse > CreateContrattoAggiuntaDitteWithHttpInfo (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization)
        {
            // verify the required parameter 'identificativoCliente' is set
            if (identificativoCliente == null)
                throw new ApiException(400, "Missing required parameter 'identificativoCliente' when calling CreazioneContrattoApi->CreateContrattoAggiuntaDitte");
            // verify the required parameter 'contratto' is set
            if (contratto == null)
                throw new ApiException(400, "Missing required parameter 'contratto' when calling CreazioneContrattoApi->CreateContrattoAggiuntaDitte");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling CreazioneContrattoApi->CreateContrattoAggiuntaDitte");

            var localVarPath = "/api/v2/contratti/{identificativoCliente}/aggiuntaditte";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (identificativoCliente != null) localVarPathParams.Add("identificativoCliente", this.Configuration.ApiClient.ParameterToString(identificativoCliente)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (contratto != null && contratto.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(contratto); // http body (model) parameter
            }
            else
            {
                localVarPostBody = contratto; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContrattoAggiuntaDitte", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateContrattoResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CreateContrattoResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateContrattoResponse)));
        }

        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of CreateContrattoResponse</returns>
        public async System.Threading.Tasks.Task<CreateContrattoResponse> CreateContrattoAggiuntaDitteAsync (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization)
        {
             ApiResponse<CreateContrattoResponse> localVarResponse = await CreateContrattoAggiuntaDitteAsyncWithHttpInfo(identificativoCliente, contratto, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Crea un contratto per aggiungere ditte ad un cliente esistente 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="identificativoCliente"></param>
        /// <param name="contratto"></param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (CreateContrattoResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateContrattoResponse>> CreateContrattoAggiuntaDitteAsyncWithHttpInfo (Guid? identificativoCliente, CreateContrattoRequest contratto, string xAuthorization)
        {
            // verify the required parameter 'identificativoCliente' is set
            if (identificativoCliente == null)
                throw new ApiException(400, "Missing required parameter 'identificativoCliente' when calling CreazioneContrattoApi->CreateContrattoAggiuntaDitte");
            // verify the required parameter 'contratto' is set
            if (contratto == null)
                throw new ApiException(400, "Missing required parameter 'contratto' when calling CreazioneContrattoApi->CreateContrattoAggiuntaDitte");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling CreazioneContrattoApi->CreateContrattoAggiuntaDitte");

            var localVarPath = "/api/v2/contratti/{identificativoCliente}/aggiuntaditte";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (identificativoCliente != null) localVarPathParams.Add("identificativoCliente", this.Configuration.ApiClient.ParameterToString(identificativoCliente)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (contratto != null && contratto.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(contratto); // http body (model) parameter
            }
            else
            {
                localVarPostBody = contratto; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContrattoAggiuntaDitte", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateContrattoResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CreateContrattoResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateContrattoResponse)));
        }

        /// <summary>
        /// Crea un contratto cliente standard 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>CreateContrattoResponse</returns>
        public CreateContrattoResponse CreateContrattoClienteStandard (CreateContrattoRequest contratto, string xAuthorization)
        {
             ApiResponse<CreateContrattoResponse> localVarResponse = CreateContrattoClienteStandardWithHttpInfo(contratto, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Crea un contratto cliente standard 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of CreateContrattoResponse</returns>
        public ApiResponse< CreateContrattoResponse > CreateContrattoClienteStandardWithHttpInfo (CreateContrattoRequest contratto, string xAuthorization)
        {
            // verify the required parameter 'contratto' is set
            if (contratto == null)
                throw new ApiException(400, "Missing required parameter 'contratto' when calling CreazioneContrattoApi->CreateContrattoClienteStandard");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling CreazioneContrattoApi->CreateContrattoClienteStandard");

            var localVarPath = "/api/v2/contratti/clientestandard";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (contratto != null && contratto.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(contratto); // http body (model) parameter
            }
            else
            {
                localVarPostBody = contratto; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContrattoClienteStandard", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateContrattoResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CreateContrattoResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateContrattoResponse)));
        }

        /// <summary>
        /// Crea un contratto cliente standard 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of CreateContrattoResponse</returns>
        public async System.Threading.Tasks.Task<CreateContrattoResponse> CreateContrattoClienteStandardAsync (CreateContrattoRequest contratto, string xAuthorization)
        {
             ApiResponse<CreateContrattoResponse> localVarResponse = await CreateContrattoClienteStandardAsyncWithHttpInfo(contratto, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Crea un contratto cliente standard 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contratto">Contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (CreateContrattoResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateContrattoResponse>> CreateContrattoClienteStandardAsyncWithHttpInfo (CreateContrattoRequest contratto, string xAuthorization)
        {
            // verify the required parameter 'contratto' is set
            if (contratto == null)
                throw new ApiException(400, "Missing required parameter 'contratto' when calling CreazioneContrattoApi->CreateContrattoClienteStandard");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling CreazioneContrattoApi->CreateContrattoClienteStandard");

            var localVarPath = "/api/v2/contratti/clientestandard";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (contratto != null && contratto.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(contratto); // http body (model) parameter
            }
            else
            {
                localVarPostBody = contratto; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContrattoClienteStandard", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateContrattoResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CreateContrattoResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateContrattoResponse)));
        }

    }
}
