/* 
 * Contratti API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetadatiApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Rimuove un metadato dalla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        void DeleteMetadato (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization);

        /// <summary>
        /// Rimuove un metadato dalla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteMetadatoWithHttpInfo (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization);
        /// <summary>
        /// Recupera i metadati della classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>MetadatiClasseDocumentaleResponse</returns>
        MetadatiClasseDocumentaleResponse GetMetadati (string id, string idAoo, string idNormativa, string xAuthorization);

        /// <summary>
        /// Recupera i metadati della classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of MetadatiClasseDocumentaleResponse</returns>
        ApiResponse<MetadatiClasseDocumentaleResponse> GetMetadatiWithHttpInfo (string id, string idAoo, string idNormativa, string xAuthorization);
        /// <summary>
        /// Aggiunge i metadati alla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        void InsertMetadati (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization);

        /// <summary>
        /// Aggiunge i metadati alla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> InsertMetadatiWithHttpInfo (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Rimuove un metadato dalla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteMetadatoAsync (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization);

        /// <summary>
        /// Rimuove un metadato dalla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteMetadatoAsyncWithHttpInfo (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization);
        /// <summary>
        /// Recupera i metadati della classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of MetadatiClasseDocumentaleResponse</returns>
        System.Threading.Tasks.Task<MetadatiClasseDocumentaleResponse> GetMetadatiAsync (string id, string idAoo, string idNormativa, string xAuthorization);

        /// <summary>
        /// Recupera i metadati della classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (MetadatiClasseDocumentaleResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MetadatiClasseDocumentaleResponse>> GetMetadatiAsyncWithHttpInfo (string id, string idAoo, string idNormativa, string xAuthorization);
        /// <summary>
        /// Aggiunge i metadati alla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task InsertMetadatiAsync (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization);

        /// <summary>
        /// Aggiunge i metadati alla classe documentale
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> InsertMetadatiAsyncWithHttpInfo (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MetadatiApi : IMetadatiApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MetadatiApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MetadatiApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetadatiApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MetadatiApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Rimuove un metadato dalla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        public void DeleteMetadato (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization)
        {
             DeleteMetadatoWithHttpInfo(id, idAoo, idNormativa, codiceCampo, xAuthorization);
        }

        /// <summary>
        /// Rimuove un metadato dalla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteMetadatoWithHttpInfo (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'idNormativa' is set
            if (idNormativa == null)
                throw new ApiException(400, "Missing required parameter 'idNormativa' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'codiceCampo' is set
            if (codiceCampo == null)
                throw new ApiException(400, "Missing required parameter 'codiceCampo' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling MetadatiApi->DeleteMetadato");

            var localVarPath = "/api/contratti/{id}/clientefinale/aoos/{idAoo}/moduli/ixce/classidocumentali/{idNormativa}/metadati/{codiceCampo}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idNormativa != null) localVarPathParams.Add("idNormativa", this.Configuration.ApiClient.ParameterToString(idNormativa)); // path parameter
            if (codiceCampo != null) localVarPathParams.Add("codiceCampo", this.Configuration.ApiClient.ParameterToString(codiceCampo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteMetadato", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Rimuove un metadato dalla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteMetadatoAsync (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization)
        {
             await DeleteMetadatoAsyncWithHttpInfo(id, idAoo, idNormativa, codiceCampo, xAuthorization);

        }

        /// <summary>
        /// Rimuove un metadato dalla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="codiceCampo">Codice campo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteMetadatoAsyncWithHttpInfo (string id, string idAoo, string idNormativa, string codiceCampo, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'idNormativa' is set
            if (idNormativa == null)
                throw new ApiException(400, "Missing required parameter 'idNormativa' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'codiceCampo' is set
            if (codiceCampo == null)
                throw new ApiException(400, "Missing required parameter 'codiceCampo' when calling MetadatiApi->DeleteMetadato");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling MetadatiApi->DeleteMetadato");

            var localVarPath = "/api/contratti/{id}/clientefinale/aoos/{idAoo}/moduli/ixce/classidocumentali/{idNormativa}/metadati/{codiceCampo}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idNormativa != null) localVarPathParams.Add("idNormativa", this.Configuration.ApiClient.ParameterToString(idNormativa)); // path parameter
            if (codiceCampo != null) localVarPathParams.Add("codiceCampo", this.Configuration.ApiClient.ParameterToString(codiceCampo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteMetadato", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Recupera i metadati della classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>MetadatiClasseDocumentaleResponse</returns>
        public MetadatiClasseDocumentaleResponse GetMetadati (string id, string idAoo, string idNormativa, string xAuthorization)
        {
             ApiResponse<MetadatiClasseDocumentaleResponse> localVarResponse = GetMetadatiWithHttpInfo(id, idAoo, idNormativa, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recupera i metadati della classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of MetadatiClasseDocumentaleResponse</returns>
        public ApiResponse< MetadatiClasseDocumentaleResponse > GetMetadatiWithHttpInfo (string id, string idAoo, string idNormativa, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling MetadatiApi->GetMetadati");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling MetadatiApi->GetMetadati");
            // verify the required parameter 'idNormativa' is set
            if (idNormativa == null)
                throw new ApiException(400, "Missing required parameter 'idNormativa' when calling MetadatiApi->GetMetadati");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling MetadatiApi->GetMetadati");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/moduli/ixce/classidocumentali/{idNormativa}/metadati";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idNormativa != null) localVarPathParams.Add("idNormativa", this.Configuration.ApiClient.ParameterToString(idNormativa)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetMetadati", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MetadatiClasseDocumentaleResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MetadatiClasseDocumentaleResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MetadatiClasseDocumentaleResponse)));
        }

        /// <summary>
        /// Recupera i metadati della classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of MetadatiClasseDocumentaleResponse</returns>
        public async System.Threading.Tasks.Task<MetadatiClasseDocumentaleResponse> GetMetadatiAsync (string id, string idAoo, string idNormativa, string xAuthorization)
        {
             ApiResponse<MetadatiClasseDocumentaleResponse> localVarResponse = await GetMetadatiAsyncWithHttpInfo(id, idAoo, idNormativa, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recupera i metadati della classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo del contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa della classe</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (MetadatiClasseDocumentaleResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MetadatiClasseDocumentaleResponse>> GetMetadatiAsyncWithHttpInfo (string id, string idAoo, string idNormativa, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling MetadatiApi->GetMetadati");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling MetadatiApi->GetMetadati");
            // verify the required parameter 'idNormativa' is set
            if (idNormativa == null)
                throw new ApiException(400, "Missing required parameter 'idNormativa' when calling MetadatiApi->GetMetadati");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling MetadatiApi->GetMetadati");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/moduli/ixce/classidocumentali/{idNormativa}/metadati";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idNormativa != null) localVarPathParams.Add("idNormativa", this.Configuration.ApiClient.ParameterToString(idNormativa)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetMetadati", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MetadatiClasseDocumentaleResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MetadatiClasseDocumentaleResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MetadatiClasseDocumentaleResponse)));
        }

        /// <summary>
        /// Aggiunge i metadati alla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        public void InsertMetadati (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization)
        {
             InsertMetadatiWithHttpInfo(id, idAoo, idNormativa, metadati, xAuthorization);
        }

        /// <summary>
        /// Aggiunge i metadati alla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> InsertMetadatiWithHttpInfo (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'idNormativa' is set
            if (idNormativa == null)
                throw new ApiException(400, "Missing required parameter 'idNormativa' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'metadati' is set
            if (metadati == null)
                throw new ApiException(400, "Missing required parameter 'metadati' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling MetadatiApi->InsertMetadati");

            var localVarPath = "/api/contratti/{id}/clientefinale/aoos/{idAoo}/moduli/ixce/classidocumentali/{idNormativa}/metadati";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idNormativa != null) localVarPathParams.Add("idNormativa", this.Configuration.ApiClient.ParameterToString(idNormativa)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (metadati != null && metadati.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(metadati); // http body (model) parameter
            }
            else
            {
                localVarPostBody = metadati; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InsertMetadati", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Aggiunge i metadati alla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task InsertMetadatiAsync (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization)
        {
             await InsertMetadatiAsyncWithHttpInfo(id, idAoo, idNormativa, metadati, xAuthorization);

        }

        /// <summary>
        /// Aggiunge i metadati alla classe documentale 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idNormativa">Id normativa</param>
        /// <param name="metadati">Metadati</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> InsertMetadatiAsyncWithHttpInfo (string id, string idAoo, string idNormativa, MetadatiClasseDocumentaleRequest metadati, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'idNormativa' is set
            if (idNormativa == null)
                throw new ApiException(400, "Missing required parameter 'idNormativa' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'metadati' is set
            if (metadati == null)
                throw new ApiException(400, "Missing required parameter 'metadati' when calling MetadatiApi->InsertMetadati");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling MetadatiApi->InsertMetadati");

            var localVarPath = "/api/contratti/{id}/clientefinale/aoos/{idAoo}/moduli/ixce/classidocumentali/{idNormativa}/metadati";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idNormativa != null) localVarPathParams.Add("idNormativa", this.Configuration.ApiClient.ParameterToString(idNormativa)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (metadati != null && metadati.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(metadati); // http body (model) parameter
            }
            else
            {
                localVarPostBody = metadati; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InsertMetadati", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
