/* 
 * Contratti API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUtentiAooApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Rimuove un utente abbinato a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        void DeleteAooUtente (string id, string idAoo, string idUtente, string xAuthorization);

        /// <summary>
        /// Rimuove un utente abbinato a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteAooUtenteWithHttpInfo (string id, string idAoo, string idUtente, string xAuthorization);
        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>AooUtenteCampiResponse</returns>
        AooUtenteCampiResponse GetAooUtenteCampi (string id, string idAoo, string xAuthorization);

        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of AooUtenteCampiResponse</returns>
        ApiResponse<AooUtenteCampiResponse> GetAooUtenteCampiWithHttpInfo (string id, string idAoo, string xAuthorization);
        /// <summary>
        /// Recupera gli utenti abbinati a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>AooUtentiResponse</returns>
        AooUtentiResponse GetAooUtenti (string id, string idAoo, string xAuthorization);

        /// <summary>
        /// Recupera gli utenti abbinati a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of AooUtentiResponse</returns>
        ApiResponse<AooUtentiResponse> GetAooUtentiWithHttpInfo (string id, string idAoo, string xAuthorization);
        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>AooUtentiDisponibiliResponse</returns>
        AooUtentiDisponibiliResponse GetUtentiDisponibili (string id, string xAuthorization);

        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of AooUtentiDisponibiliResponse</returns>
        ApiResponse<AooUtentiDisponibiliResponse> GetUtentiDisponibiliWithHttpInfo (string id, string xAuthorization);
        /// <summary>
        /// Aggiunge gli utenti a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        void InsertAooUtenti (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization);

        /// <summary>
        /// Aggiunge gli utenti a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> InsertAooUtentiWithHttpInfo (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Rimuove un utente abbinato a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteAooUtenteAsync (string id, string idAoo, string idUtente, string xAuthorization);

        /// <summary>
        /// Rimuove un utente abbinato a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAooUtenteAsyncWithHttpInfo (string id, string idAoo, string idUtente, string xAuthorization);
        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of AooUtenteCampiResponse</returns>
        System.Threading.Tasks.Task<AooUtenteCampiResponse> GetAooUtenteCampiAsync (string id, string idAoo, string xAuthorization);

        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (AooUtenteCampiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AooUtenteCampiResponse>> GetAooUtenteCampiAsyncWithHttpInfo (string id, string idAoo, string xAuthorization);
        /// <summary>
        /// Recupera gli utenti abbinati a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of AooUtentiResponse</returns>
        System.Threading.Tasks.Task<AooUtentiResponse> GetAooUtentiAsync (string id, string idAoo, string xAuthorization);

        /// <summary>
        /// Recupera gli utenti abbinati a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (AooUtentiResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AooUtentiResponse>> GetAooUtentiAsyncWithHttpInfo (string id, string idAoo, string xAuthorization);
        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of AooUtentiDisponibiliResponse</returns>
        System.Threading.Tasks.Task<AooUtentiDisponibiliResponse> GetUtentiDisponibiliAsync (string id, string xAuthorization);

        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (AooUtentiDisponibiliResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AooUtentiDisponibiliResponse>> GetUtentiDisponibiliAsyncWithHttpInfo (string id, string xAuthorization);
        /// <summary>
        /// Aggiunge gli utenti a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task InsertAooUtentiAsync (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization);

        /// <summary>
        /// Aggiunge gli utenti a una aoo
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> InsertAooUtentiAsyncWithHttpInfo (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UtentiAooApi : IUtentiAooApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UtentiAooApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UtentiAooApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtentiAooApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UtentiAooApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Rimuove un utente abbinato a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        public void DeleteAooUtente (string id, string idAoo, string idUtente, string xAuthorization)
        {
             DeleteAooUtenteWithHttpInfo(id, idAoo, idUtente, xAuthorization);
        }

        /// <summary>
        /// Rimuove un utente abbinato a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteAooUtenteWithHttpInfo (string id, string idAoo, string idUtente, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->DeleteAooUtente");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->DeleteAooUtente");
            // verify the required parameter 'idUtente' is set
            if (idUtente == null)
                throw new ApiException(400, "Missing required parameter 'idUtente' when calling UtentiAooApi->DeleteAooUtente");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->DeleteAooUtente");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/utenti/{idUtente}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idUtente != null) localVarPathParams.Add("idUtente", this.Configuration.ApiClient.ParameterToString(idUtente)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAooUtente", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Rimuove un utente abbinato a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteAooUtenteAsync (string id, string idAoo, string idUtente, string xAuthorization)
        {
             await DeleteAooUtenteAsyncWithHttpInfo(id, idAoo, idUtente, xAuthorization);

        }

        /// <summary>
        /// Rimuove un utente abbinato a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="idUtente">Identificativo utente</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAooUtenteAsyncWithHttpInfo (string id, string idAoo, string idUtente, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->DeleteAooUtente");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->DeleteAooUtente");
            // verify the required parameter 'idUtente' is set
            if (idUtente == null)
                throw new ApiException(400, "Missing required parameter 'idUtente' when calling UtentiAooApi->DeleteAooUtente");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->DeleteAooUtente");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/utenti/{idUtente}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (idUtente != null) localVarPathParams.Add("idUtente", this.Configuration.ApiClient.ParameterToString(idUtente)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAooUtente", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>AooUtenteCampiResponse</returns>
        public AooUtenteCampiResponse GetAooUtenteCampi (string id, string idAoo, string xAuthorization)
        {
             ApiResponse<AooUtenteCampiResponse> localVarResponse = GetAooUtenteCampiWithHttpInfo(id, idAoo, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of AooUtenteCampiResponse</returns>
        public ApiResponse< AooUtenteCampiResponse > GetAooUtenteCampiWithHttpInfo (string id, string idAoo, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->GetAooUtenteCampi");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->GetAooUtenteCampi");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->GetAooUtenteCampi");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/anagrafiche/aoos/{idAoo}/utenti/campi";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAooUtenteCampi", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUtenteCampiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUtenteCampiResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUtenteCampiResponse)));
        }

        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of AooUtenteCampiResponse</returns>
        public async System.Threading.Tasks.Task<AooUtenteCampiResponse> GetAooUtenteCampiAsync (string id, string idAoo, string xAuthorization)
        {
             ApiResponse<AooUtenteCampiResponse> localVarResponse = await GetAooUtenteCampiAsyncWithHttpInfo(id, idAoo, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recupera i campi disponibili per l&#39;associazione di un utente a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (AooUtenteCampiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AooUtenteCampiResponse>> GetAooUtenteCampiAsyncWithHttpInfo (string id, string idAoo, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->GetAooUtenteCampi");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->GetAooUtenteCampi");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->GetAooUtenteCampi");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/anagrafiche/aoos/{idAoo}/utenti/campi";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAooUtenteCampi", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUtenteCampiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUtenteCampiResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUtenteCampiResponse)));
        }

        /// <summary>
        /// Recupera gli utenti abbinati a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>AooUtentiResponse</returns>
        public AooUtentiResponse GetAooUtenti (string id, string idAoo, string xAuthorization)
        {
             ApiResponse<AooUtentiResponse> localVarResponse = GetAooUtentiWithHttpInfo(id, idAoo, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recupera gli utenti abbinati a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of AooUtentiResponse</returns>
        public ApiResponse< AooUtentiResponse > GetAooUtentiWithHttpInfo (string id, string idAoo, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->GetAooUtenti");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->GetAooUtenti");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->GetAooUtenti");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/utenti";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAooUtenti", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUtentiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUtentiResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUtentiResponse)));
        }

        /// <summary>
        /// Recupera gli utenti abbinati a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of AooUtentiResponse</returns>
        public async System.Threading.Tasks.Task<AooUtentiResponse> GetAooUtentiAsync (string id, string idAoo, string xAuthorization)
        {
             ApiResponse<AooUtentiResponse> localVarResponse = await GetAooUtentiAsyncWithHttpInfo(id, idAoo, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recupera gli utenti abbinati a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (AooUtentiResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AooUtentiResponse>> GetAooUtentiAsyncWithHttpInfo (string id, string idAoo, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->GetAooUtenti");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->GetAooUtenti");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->GetAooUtenti");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/utenti";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAooUtenti", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUtentiResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUtentiResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUtentiResponse)));
        }

        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>AooUtentiDisponibiliResponse</returns>
        public AooUtentiDisponibiliResponse GetUtentiDisponibili (string id, string xAuthorization)
        {
             ApiResponse<AooUtentiDisponibiliResponse> localVarResponse = GetUtentiDisponibiliWithHttpInfo(id, xAuthorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of AooUtentiDisponibiliResponse</returns>
        public ApiResponse< AooUtentiDisponibiliResponse > GetUtentiDisponibiliWithHttpInfo (string id, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->GetUtentiDisponibili");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->GetUtentiDisponibili");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/anagrafiche/aoos/utenti/utentidisponibili";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUtentiDisponibili", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUtentiDisponibiliResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUtentiDisponibiliResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUtentiDisponibiliResponse)));
        }

        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of AooUtentiDisponibiliResponse</returns>
        public async System.Threading.Tasks.Task<AooUtentiDisponibiliResponse> GetUtentiDisponibiliAsync (string id, string xAuthorization)
        {
             ApiResponse<AooUtentiDisponibiliResponse> localVarResponse = await GetUtentiDisponibiliAsyncWithHttpInfo(id, xAuthorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recupera gli utenti disponibili per l&#39;associazione con una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse (AooUtentiDisponibiliResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AooUtentiDisponibiliResponse>> GetUtentiDisponibiliAsyncWithHttpInfo (string id, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->GetUtentiDisponibili");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->GetUtentiDisponibili");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/anagrafiche/aoos/utenti/utentidisponibili";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUtentiDisponibili", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AooUtentiDisponibiliResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AooUtentiDisponibiliResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AooUtentiDisponibiliResponse)));
        }

        /// <summary>
        /// Aggiunge gli utenti a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns></returns>
        public void InsertAooUtenti (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization)
        {
             InsertAooUtentiWithHttpInfo(id, idAoo, utenti, xAuthorization);
        }

        /// <summary>
        /// Aggiunge gli utenti a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> InsertAooUtentiWithHttpInfo (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->InsertAooUtenti");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->InsertAooUtenti");
            // verify the required parameter 'utenti' is set
            if (utenti == null)
                throw new ApiException(400, "Missing required parameter 'utenti' when calling UtentiAooApi->InsertAooUtenti");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->InsertAooUtenti");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/utenti";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (utenti != null && utenti.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(utenti); // http body (model) parameter
            }
            else
            {
                localVarPostBody = utenti; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InsertAooUtenti", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Aggiunge gli utenti a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task InsertAooUtentiAsync (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization)
        {
             await InsertAooUtentiAsyncWithHttpInfo(id, idAoo, utenti, xAuthorization);

        }

        /// <summary>
        /// Aggiunge gli utenti a una aoo 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Identificativo contratto</param>
        /// <param name="idAoo">Identificativo aoo</param>
        /// <param name="utenti">Utenti da abbinare all&#39;aoo</param>
        /// <param name="xAuthorization">access_token</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> InsertAooUtentiAsyncWithHttpInfo (string id, string idAoo, AooUtentiRequest utenti, string xAuthorization)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling UtentiAooApi->InsertAooUtenti");
            // verify the required parameter 'idAoo' is set
            if (idAoo == null)
                throw new ApiException(400, "Missing required parameter 'idAoo' when calling UtentiAooApi->InsertAooUtenti");
            // verify the required parameter 'utenti' is set
            if (utenti == null)
                throw new ApiException(400, "Missing required parameter 'utenti' when calling UtentiAooApi->InsertAooUtenti");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling UtentiAooApi->InsertAooUtenti");

            var localVarPath = "/api/v1/contratti/{id}/clientefinale/aoos/{idAoo}/utenti";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (idAoo != null) localVarPathParams.Add("idAoo", this.Configuration.ApiClient.ParameterToString(idAoo)); // path parameter
            if (xAuthorization != null) localVarHeaderParams.Add("X-Authorization", this.Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (utenti != null && utenti.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(utenti); // http body (model) parameter
            }
            else
            {
                localVarPostBody = utenti; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InsertAooUtenti", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
